//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemEkzDemo.ModelDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientServiceGood
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientServiceGood()
        {
            this.DocumentByServices = new HashSet<DocumentByService>();
            this.ProductSales = new HashSet<ProductSale>();
        }
    
        public int ID { get; set; }
        public string Client { get; set; }
        public Nullable<System.DateTime> StartServiceTime { get; set; }
        public string Service { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> ServiceID { get; set; }
    
        public virtual Client_Import_good Client_Import_good { get; set; }
        public virtual Service_good Service_good { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentByService> DocumentByServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSale> ProductSales { get; set; }
    }
}
